.TH MPI_Type_c2f 3 "10/6/2025" " " "MPI"
.SH NAME
MPI_Type_c2f \-  converts MPI_Type to Fortran INTEGER 
.SH SYNOPSIS
.nf
.fi
.nf
MPI_Fint MPI_Type_c2f(MPI_Datatype datatype)
.fi


.SH INPUT PARAMETERS
.PD 0
.TP
.B datatype 
- datatype (handle)
.PD 1

.SH THREAD AND INTERRUPT SAFETY

This routine is thread-safe.  This means that this routine may be
safely used by multiple threads without the need for any user-provided
thread locks.  However, the routine is not interrupt safe.  Typically,
this is due to the use of memory allocation routines such as 
.I malloc
or other non-MPICH runtime routines that are themselves not interrupt-safe.

