##
## Copyright (C) by Argonne National Laboratory
##     See COPYRIGHT in top-level directory
##

# -- THIS FILE IS AUTO-GENERATED -- 

mpi_sources += \
    src/binding/c/async/async_start.c \
    src/binding/c/async/async_get_state.c \
    src/binding/c/async/async_spawn.c \
    src/binding/c/attr/comm_create_keyval.c \
    src/binding/c/attr/comm_delete_attr.c \
    src/binding/c/attr/comm_free_keyval.c \
    src/binding/c/attr/comm_get_attr.c \
    src/binding/c/attr/comm_set_attr.c \
    src/binding/c/attr/type_create_keyval.c \
    src/binding/c/attr/type_delete_attr.c \
    src/binding/c/attr/type_free_keyval.c \
    src/binding/c/attr/type_get_attr.c \
    src/binding/c/attr/type_set_attr.c \
    src/binding/c/attr/win_create_keyval.c \
    src/binding/c/attr/win_delete_attr.c \
    src/binding/c/attr/win_free_keyval.c \
    src/binding/c/attr/win_get_attr.c \
    src/binding/c/attr/win_set_attr.c \
    src/binding/c/binding/op_create_x.c \
    src/binding/c/binding/comm_create_errhandler_x.c \
    src/binding/c/binding/win_create_errhandler_x.c \
    src/binding/c/binding/file_create_errhandler_x.c \
    src/binding/c/binding/session_create_errhandler_x.c \
    src/binding/c/coll/allgather.c \
    src/binding/c/coll/allgather_init.c \
    src/binding/c/coll/allgatherv.c \
    src/binding/c/coll/allgatherv_init.c \
    src/binding/c/coll/allreduce.c \
    src/binding/c/coll/allreduce_init.c \
    src/binding/c/coll/alltoall.c \
    src/binding/c/coll/alltoall_init.c \
    src/binding/c/coll/alltoallv.c \
    src/binding/c/coll/alltoallv_init.c \
    src/binding/c/coll/alltoallw.c \
    src/binding/c/coll/alltoallw_init.c \
    src/binding/c/coll/barrier.c \
    src/binding/c/coll/barrier_init.c \
    src/binding/c/coll/bcast.c \
    src/binding/c/coll/bcast_init.c \
    src/binding/c/coll/exscan.c \
    src/binding/c/coll/exscan_init.c \
    src/binding/c/coll/gather.c \
    src/binding/c/coll/gather_init.c \
    src/binding/c/coll/gatherv.c \
    src/binding/c/coll/gatherv_init.c \
    src/binding/c/coll/iallgather.c \
    src/binding/c/coll/iallgatherv.c \
    src/binding/c/coll/iallreduce.c \
    src/binding/c/coll/ialltoall.c \
    src/binding/c/coll/ialltoallv.c \
    src/binding/c/coll/ialltoallw.c \
    src/binding/c/coll/ibarrier.c \
    src/binding/c/coll/ibcast.c \
    src/binding/c/coll/iexscan.c \
    src/binding/c/coll/igather.c \
    src/binding/c/coll/igatherv.c \
    src/binding/c/coll/ineighbor_allgather.c \
    src/binding/c/coll/ineighbor_allgatherv.c \
    src/binding/c/coll/ineighbor_alltoall.c \
    src/binding/c/coll/ineighbor_alltoallv.c \
    src/binding/c/coll/ineighbor_alltoallw.c \
    src/binding/c/coll/ireduce.c \
    src/binding/c/coll/ireduce_scatter.c \
    src/binding/c/coll/ireduce_scatter_block.c \
    src/binding/c/coll/iscan.c \
    src/binding/c/coll/iscatter.c \
    src/binding/c/coll/iscatterv.c \
    src/binding/c/coll/neighbor_allgather.c \
    src/binding/c/coll/neighbor_allgather_init.c \
    src/binding/c/coll/neighbor_allgatherv.c \
    src/binding/c/coll/neighbor_allgatherv_init.c \
    src/binding/c/coll/neighbor_alltoall.c \
    src/binding/c/coll/neighbor_alltoall_init.c \
    src/binding/c/coll/neighbor_alltoallv.c \
    src/binding/c/coll/neighbor_alltoallv_init.c \
    src/binding/c/coll/neighbor_alltoallw.c \
    src/binding/c/coll/neighbor_alltoallw_init.c \
    src/binding/c/coll/reduce.c \
    src/binding/c/coll/reduce_init.c \
    src/binding/c/coll/reduce_local.c \
    src/binding/c/coll/reduce_scatter.c \
    src/binding/c/coll/reduce_scatter_block.c \
    src/binding/c/coll/reduce_scatter_block_init.c \
    src/binding/c/coll/reduce_scatter_init.c \
    src/binding/c/coll/scan.c \
    src/binding/c/coll/scan_init.c \
    src/binding/c/coll/scatter.c \
    src/binding/c/coll/scatter_init.c \
    src/binding/c/coll/scatterv.c \
    src/binding/c/coll/scatterv_init.c \
    src/binding/c/comm/comm_compare.c \
    src/binding/c/comm/comm_create.c \
    src/binding/c/comm/comm_create_group.c \
    src/binding/c/comm/comm_dup.c \
    src/binding/c/comm/comm_dup_with_info.c \
    src/binding/c/comm/comm_free.c \
    src/binding/c/comm/comm_get_info.c \
    src/binding/c/comm/comm_get_name.c \
    src/binding/c/comm/comm_group.c \
    src/binding/c/comm/comm_idup.c \
    src/binding/c/comm/comm_idup_with_info.c \
    src/binding/c/comm/comm_rank.c \
    src/binding/c/comm/comm_remote_group.c \
    src/binding/c/comm/comm_remote_size.c \
    src/binding/c/comm/comm_set_info.c \
    src/binding/c/comm/comm_set_name.c \
    src/binding/c/comm/comm_size.c \
    src/binding/c/comm/comm_split.c \
    src/binding/c/comm/comm_split_type.c \
    src/binding/c/comm/comm_test_inter.c \
    src/binding/c/comm/intercomm_create.c \
    src/binding/c/comm/intercomm_create_from_groups.c \
    src/binding/c/comm/intercomm_merge.c \
    src/binding/c/comm/comm_test_threadcomm.c \
    src/binding/c/comm/comm_revoke.c \
    src/binding/c/comm/comm_shrink.c \
    src/binding/c/comm/comm_failure_ack.c \
    src/binding/c/comm/comm_failure_get_acked.c \
    src/binding/c/comm/comm_agree.c \
    src/binding/c/comm/comm_get_failed.c \
    src/binding/c/datatype/get_address.c \
    src/binding/c/datatype/get_count.c \
    src/binding/c/datatype/get_elements.c \
    src/binding/c/datatype/get_elements_x.c \
    src/binding/c/datatype/pack.c \
    src/binding/c/datatype/pack_external.c \
    src/binding/c/datatype/pack_external_size.c \
    src/binding/c/datatype/pack_size.c \
    src/binding/c/datatype/status_set_elements.c \
    src/binding/c/datatype/status_set_elements_x.c \
    src/binding/c/datatype/type_commit.c \
    src/binding/c/datatype/type_contiguous.c \
    src/binding/c/datatype/type_create_darray.c \
    src/binding/c/datatype/type_create_f90_complex.c \
    src/binding/c/datatype/type_create_f90_integer.c \
    src/binding/c/datatype/type_create_f90_real.c \
    src/binding/c/datatype/type_create_hindexed.c \
    src/binding/c/datatype/type_create_hindexed_block.c \
    src/binding/c/datatype/type_create_hvector.c \
    src/binding/c/datatype/type_create_indexed_block.c \
    src/binding/c/datatype/type_create_resized.c \
    src/binding/c/datatype/type_create_struct.c \
    src/binding/c/datatype/type_create_subarray.c \
    src/binding/c/datatype/type_dup.c \
    src/binding/c/datatype/type_free.c \
    src/binding/c/datatype/type_get_contents.c \
    src/binding/c/datatype/type_get_envelope.c \
    src/binding/c/datatype/type_get_extent.c \
    src/binding/c/datatype/type_get_extent_x.c \
    src/binding/c/datatype/type_get_name.c \
    src/binding/c/datatype/type_get_true_extent.c \
    src/binding/c/datatype/type_get_true_extent_x.c \
    src/binding/c/datatype/type_get_value_index.c \
    src/binding/c/datatype/type_indexed.c \
    src/binding/c/datatype/type_match_size.c \
    src/binding/c/datatype/type_set_name.c \
    src/binding/c/datatype/type_size.c \
    src/binding/c/datatype/type_size_x.c \
    src/binding/c/datatype/type_vector.c \
    src/binding/c/datatype/unpack.c \
    src/binding/c/datatype/unpack_external.c \
    src/binding/c/datatype/type_extent.c \
    src/binding/c/datatype/type_lb.c \
    src/binding/c/datatype/type_ub.c \
    src/binding/c/datatype/type_iov_len.c \
    src/binding/c/datatype/type_iov.c \
    src/binding/c/errhan/add_error_class.c \
    src/binding/c/errhan/add_error_code.c \
    src/binding/c/errhan/add_error_string.c \
    src/binding/c/errhan/comm_call_errhandler.c \
    src/binding/c/errhan/comm_create_errhandler.c \
    src/binding/c/errhan/comm_get_errhandler.c \
    src/binding/c/errhan/comm_set_errhandler.c \
    src/binding/c/errhan/errhandler_free.c \
    src/binding/c/errhan/error_class.c \
    src/binding/c/errhan/error_string.c \
    src/binding/c/errhan/file_call_errhandler.c \
    src/binding/c/errhan/file_create_errhandler.c \
    src/binding/c/errhan/file_get_errhandler.c \
    src/binding/c/errhan/file_set_errhandler.c \
    src/binding/c/errhan/remove_error_class.c \
    src/binding/c/errhan/remove_error_code.c \
    src/binding/c/errhan/remove_error_string.c \
    src/binding/c/errhan/session_call_errhandler.c \
    src/binding/c/errhan/session_create_errhandler.c \
    src/binding/c/errhan/session_get_errhandler.c \
    src/binding/c/errhan/session_set_errhandler.c \
    src/binding/c/errhan/win_call_errhandler.c \
    src/binding/c/errhan/win_create_errhandler.c \
    src/binding/c/errhan/win_get_errhandler.c \
    src/binding/c/errhan/win_set_errhandler.c \
    src/binding/c/f2c/comm_c2f.c \
    src/binding/c/f2c/comm_f2c.c \
    src/binding/c/f2c/errhandler_c2f.c \
    src/binding/c/f2c/errhandler_f2c.c \
    src/binding/c/f2c/group_c2f.c \
    src/binding/c/f2c/group_f2c.c \
    src/binding/c/f2c/info_c2f.c \
    src/binding/c/f2c/info_f2c.c \
    src/binding/c/f2c/message_c2f.c \
    src/binding/c/f2c/message_f2c.c \
    src/binding/c/f2c/op_c2f.c \
    src/binding/c/f2c/op_f2c.c \
    src/binding/c/f2c/request_c2f.c \
    src/binding/c/f2c/request_f2c.c \
    src/binding/c/f2c/session_c2f.c \
    src/binding/c/f2c/session_f2c.c \
    src/binding/c/f2c/status_c2f.c \
    src/binding/c/f2c/status_c2f08.c \
    src/binding/c/f2c/status_f082c.c \
    src/binding/c/f2c/status_f082f.c \
    src/binding/c/f2c/status_f2c.c \
    src/binding/c/f2c/status_f2f08.c \
    src/binding/c/f2c/type_c2f.c \
    src/binding/c/f2c/type_f2c.c \
    src/binding/c/f2c/win_c2f.c \
    src/binding/c/f2c/win_f2c.c \
    src/binding/c/group/group_compare.c \
    src/binding/c/group/group_difference.c \
    src/binding/c/group/group_excl.c \
    src/binding/c/group/group_free.c \
    src/binding/c/group/group_incl.c \
    src/binding/c/group/group_intersection.c \
    src/binding/c/group/group_range_excl.c \
    src/binding/c/group/group_range_incl.c \
    src/binding/c/group/group_rank.c \
    src/binding/c/group/group_size.c \
    src/binding/c/group/group_translate_ranks.c \
    src/binding/c/group/group_union.c \
    src/binding/c/info/info_create.c \
    src/binding/c/info/info_create_env.c \
    src/binding/c/info/info_delete.c \
    src/binding/c/info/info_dup.c \
    src/binding/c/info/info_free.c \
    src/binding/c/info/info_get.c \
    src/binding/c/info/info_get_nkeys.c \
    src/binding/c/info/info_get_nthkey.c \
    src/binding/c/info/info_get_string.c \
    src/binding/c/info/info_get_valuelen.c \
    src/binding/c/info/info_set.c \
    src/binding/c/info/info_set_hex.c \
    src/binding/c/init/abort.c \
    src/binding/c/init/comm_create_from_group.c \
    src/binding/c/init/finalize.c \
    src/binding/c/init/finalized.c \
    src/binding/c/init/group_from_session_pset.c \
    src/binding/c/init/init.c \
    src/binding/c/init/init_thread.c \
    src/binding/c/init/initialized.c \
    src/binding/c/init/is_thread_main.c \
    src/binding/c/init/query_thread.c \
    src/binding/c/init/session_finalize.c \
    src/binding/c/init/session_get_info.c \
    src/binding/c/init/session_get_nth_pset.c \
    src/binding/c/init/session_get_num_psets.c \
    src/binding/c/init/session_get_pset_info.c \
    src/binding/c/init/session_init.c \
    src/binding/c/misc/aint_add.c \
    src/binding/c/misc/aint_diff.c \
    src/binding/c/misc/get_library_version.c \
    src/binding/c/misc/get_processor_name.c \
    src/binding/c/misc/get_version.c \
    src/binding/c/misc/pcontrol.c \
    src/binding/c/misc/gpu_query_support.c \
    src/binding/c/misc/query_cuda_support.c \
    src/binding/c/misc/query_ze_support.c \
    src/binding/c/misc/query_hip_support.c \
    src/binding/c/mpit/category_changed.c \
    src/binding/c/mpit/category_get_categories.c \
    src/binding/c/mpit/category_get_cvars.c \
    src/binding/c/mpit/category_get_events.c \
    src/binding/c/mpit/category_get_index.c \
    src/binding/c/mpit/category_get_info.c \
    src/binding/c/mpit/category_get_num.c \
    src/binding/c/mpit/category_get_num_events.c \
    src/binding/c/mpit/category_get_pvars.c \
    src/binding/c/mpit/cvar_get_index.c \
    src/binding/c/mpit/cvar_get_info.c \
    src/binding/c/mpit/cvar_get_num.c \
    src/binding/c/mpit/cvar_handle_alloc.c \
    src/binding/c/mpit/cvar_handle_free.c \
    src/binding/c/mpit/cvar_read.c \
    src/binding/c/mpit/cvar_write.c \
    src/binding/c/mpit/enum_get_info.c \
    src/binding/c/mpit/enum_get_item.c \
    src/binding/c/mpit/event_callback_get_info.c \
    src/binding/c/mpit/event_callback_set_info.c \
    src/binding/c/mpit/event_copy.c \
    src/binding/c/mpit/event_get_index.c \
    src/binding/c/mpit/event_get_info.c \
    src/binding/c/mpit/event_get_num.c \
    src/binding/c/mpit/event_get_source.c \
    src/binding/c/mpit/event_get_timestamp.c \
    src/binding/c/mpit/event_handle_alloc.c \
    src/binding/c/mpit/event_handle_free.c \
    src/binding/c/mpit/event_handle_get_info.c \
    src/binding/c/mpit/event_handle_set_info.c \
    src/binding/c/mpit/event_read.c \
    src/binding/c/mpit/event_register_callback.c \
    src/binding/c/mpit/event_set_dropped_handler.c \
    src/binding/c/mpit/finalize.c \
    src/binding/c/mpit/init_thread.c \
    src/binding/c/mpit/pvar_get_index.c \
    src/binding/c/mpit/pvar_get_info.c \
    src/binding/c/mpit/pvar_get_num.c \
    src/binding/c/mpit/pvar_handle_alloc.c \
    src/binding/c/mpit/pvar_handle_free.c \
    src/binding/c/mpit/pvar_read.c \
    src/binding/c/mpit/pvar_readreset.c \
    src/binding/c/mpit/pvar_reset.c \
    src/binding/c/mpit/pvar_session_create.c \
    src/binding/c/mpit/pvar_session_free.c \
    src/binding/c/mpit/pvar_start.c \
    src/binding/c/mpit/pvar_stop.c \
    src/binding/c/mpit/pvar_write.c \
    src/binding/c/mpit/source_get_info.c \
    src/binding/c/mpit/source_get_num.c \
    src/binding/c/mpit/source_get_timestamp.c \
    src/binding/c/op/op_commutative.c \
    src/binding/c/op/op_create.c \
    src/binding/c/op/op_free.c \
    src/binding/c/part/parrived.c \
    src/binding/c/part/pready.c \
    src/binding/c/part/pready_list.c \
    src/binding/c/part/pready_range.c \
    src/binding/c/part/precv_init.c \
    src/binding/c/part/psend_init.c \
    src/binding/c/pt2pt/bsend.c \
    src/binding/c/pt2pt/bsend_init.c \
    src/binding/c/pt2pt/buffer_attach.c \
    src/binding/c/pt2pt/buffer_detach.c \
    src/binding/c/pt2pt/buffer_flush.c \
    src/binding/c/pt2pt/buffer_iflush.c \
    src/binding/c/pt2pt/comm_attach_buffer.c \
    src/binding/c/pt2pt/comm_detach_buffer.c \
    src/binding/c/pt2pt/comm_flush_buffer.c \
    src/binding/c/pt2pt/comm_iflush_buffer.c \
    src/binding/c/pt2pt/ibsend.c \
    src/binding/c/pt2pt/improbe.c \
    src/binding/c/pt2pt/imrecv.c \
    src/binding/c/pt2pt/iprobe.c \
    src/binding/c/pt2pt/irecv.c \
    src/binding/c/pt2pt/irsend.c \
    src/binding/c/pt2pt/isend.c \
    src/binding/c/pt2pt/isendrecv.c \
    src/binding/c/pt2pt/isendrecv_replace.c \
    src/binding/c/pt2pt/issend.c \
    src/binding/c/pt2pt/mprobe.c \
    src/binding/c/pt2pt/mrecv.c \
    src/binding/c/pt2pt/probe.c \
    src/binding/c/pt2pt/recv.c \
    src/binding/c/pt2pt/recv_init.c \
    src/binding/c/pt2pt/rsend.c \
    src/binding/c/pt2pt/rsend_init.c \
    src/binding/c/pt2pt/send.c \
    src/binding/c/pt2pt/send_init.c \
    src/binding/c/pt2pt/sendrecv.c \
    src/binding/c/pt2pt/sendrecv_replace.c \
    src/binding/c/pt2pt/session_attach_buffer.c \
    src/binding/c/pt2pt/session_detach_buffer.c \
    src/binding/c/pt2pt/session_flush_buffer.c \
    src/binding/c/pt2pt/session_iflush_buffer.c \
    src/binding/c/pt2pt/ssend.c \
    src/binding/c/pt2pt/ssend_init.c \
    src/binding/c/request/cancel.c \
    src/binding/c/request/grequest_complete.c \
    src/binding/c/request/grequest_start.c \
    src/binding/c/request/request_free.c \
    src/binding/c/request/request_get_status.c \
    src/binding/c/request/request_get_status_all.c \
    src/binding/c/request/request_get_status_any.c \
    src/binding/c/request/request_get_status_some.c \
    src/binding/c/request/start.c \
    src/binding/c/request/startall.c \
    src/binding/c/request/status_get_error.c \
    src/binding/c/request/status_get_source.c \
    src/binding/c/request/status_get_tag.c \
    src/binding/c/request/status_set_error.c \
    src/binding/c/request/status_set_source.c \
    src/binding/c/request/status_set_tag.c \
    src/binding/c/request/status_set_cancelled.c \
    src/binding/c/request/test.c \
    src/binding/c/request/test_cancelled.c \
    src/binding/c/request/testall.c \
    src/binding/c/request/testany.c \
    src/binding/c/request/testsome.c \
    src/binding/c/request/wait.c \
    src/binding/c/request/waitall.c \
    src/binding/c/request/waitany.c \
    src/binding/c/request/waitsome.c \
    src/binding/c/request/grequest_start_x.c \
    src/binding/c/request/grequest_class_create.c \
    src/binding/c/request/grequest_class_allocate.c \
    src/binding/c/request/request_is_complete.c \
    src/binding/c/rma/accumulate.c \
    src/binding/c/rma/alloc_mem.c \
    src/binding/c/rma/compare_and_swap.c \
    src/binding/c/rma/fetch_and_op.c \
    src/binding/c/rma/free_mem.c \
    src/binding/c/rma/get.c \
    src/binding/c/rma/get_accumulate.c \
    src/binding/c/rma/put.c \
    src/binding/c/rma/raccumulate.c \
    src/binding/c/rma/rget.c \
    src/binding/c/rma/rget_accumulate.c \
    src/binding/c/rma/rput.c \
    src/binding/c/rma/win_allocate.c \
    src/binding/c/rma/win_allocate_shared.c \
    src/binding/c/rma/win_attach.c \
    src/binding/c/rma/win_complete.c \
    src/binding/c/rma/win_create.c \
    src/binding/c/rma/win_create_dynamic.c \
    src/binding/c/rma/win_detach.c \
    src/binding/c/rma/win_fence.c \
    src/binding/c/rma/win_flush.c \
    src/binding/c/rma/win_flush_all.c \
    src/binding/c/rma/win_flush_local.c \
    src/binding/c/rma/win_flush_local_all.c \
    src/binding/c/rma/win_free.c \
    src/binding/c/rma/win_get_group.c \
    src/binding/c/rma/win_get_info.c \
    src/binding/c/rma/win_get_name.c \
    src/binding/c/rma/win_lock.c \
    src/binding/c/rma/win_lock_all.c \
    src/binding/c/rma/win_post.c \
    src/binding/c/rma/win_set_info.c \
    src/binding/c/rma/win_set_name.c \
    src/binding/c/rma/win_shared_query.c \
    src/binding/c/rma/win_start.c \
    src/binding/c/rma/win_sync.c \
    src/binding/c/rma/win_test.c \
    src/binding/c/rma/win_unlock.c \
    src/binding/c/rma/win_unlock_all.c \
    src/binding/c/rma/win_wait.c \
    src/binding/c/spawn/close_port.c \
    src/binding/c/spawn/comm_accept.c \
    src/binding/c/spawn/comm_connect.c \
    src/binding/c/spawn/comm_disconnect.c \
    src/binding/c/spawn/comm_get_parent.c \
    src/binding/c/spawn/comm_join.c \
    src/binding/c/spawn/comm_spawn.c \
    src/binding/c/spawn/comm_spawn_multiple.c \
    src/binding/c/spawn/lookup_name.c \
    src/binding/c/spawn/open_port.c \
    src/binding/c/spawn/publish_name.c \
    src/binding/c/spawn/unpublish_name.c \
    src/binding/c/stream/stream_create.c \
    src/binding/c/stream/stream_free.c \
    src/binding/c/stream/stream_comm_create.c \
    src/binding/c/stream/stream_comm_create_multiplex.c \
    src/binding/c/stream/comm_get_stream.c \
    src/binding/c/stream/stream_progress.c \
    src/binding/c/stream/start_progress_thread.c \
    src/binding/c/stream/stop_progress_thread.c \
    src/binding/c/stream/stream_send.c \
    src/binding/c/stream/stream_isend.c \
    src/binding/c/stream/stream_recv.c \
    src/binding/c/stream/stream_irecv.c \
    src/binding/c/stream/send_enqueue.c \
    src/binding/c/stream/recv_enqueue.c \
    src/binding/c/stream/isend_enqueue.c \
    src/binding/c/stream/irecv_enqueue.c \
    src/binding/c/stream/wait_enqueue.c \
    src/binding/c/stream/waitall_enqueue.c \
    src/binding/c/stream/allreduce_enqueue.c \
    src/binding/c/threadcomm/threadcomm_init.c \
    src/binding/c/threadcomm/threadcomm_free.c \
    src/binding/c/threadcomm/threadcomm_start.c \
    src/binding/c/threadcomm/threadcomm_finish.c \
    src/binding/c/timer/wtick.c \
    src/binding/c/timer/wtime.c \
    src/binding/c/topo/cart_coords.c \
    src/binding/c/topo/cart_create.c \
    src/binding/c/topo/cart_get.c \
    src/binding/c/topo/cart_map.c \
    src/binding/c/topo/cart_rank.c \
    src/binding/c/topo/cart_shift.c \
    src/binding/c/topo/cart_sub.c \
    src/binding/c/topo/cartdim_get.c \
    src/binding/c/topo/dims_create.c \
    src/binding/c/topo/dist_graph_create.c \
    src/binding/c/topo/dist_graph_create_adjacent.c \
    src/binding/c/topo/dist_graph_neighbors.c \
    src/binding/c/topo/dist_graph_neighbors_count.c \
    src/binding/c/topo/get_hw_resource_info.c \
    src/binding/c/topo/graph_create.c \
    src/binding/c/topo/graph_get.c \
    src/binding/c/topo/graph_map.c \
    src/binding/c/topo/graph_neighbors.c \
    src/binding/c/topo/graph_neighbors_count.c \
    src/binding/c/topo/graphdims_get.c \
    src/binding/c/topo/topo_test.c
doc3_src_txt += \
    src/binding/c/mansrc/mpix_async_start.txt \
    src/binding/c/mansrc/mpix_async_get_state.txt \
    src/binding/c/mansrc/mpix_async_spawn.txt \
    src/binding/c/mansrc/mpi_comm_create_keyval.txt \
    src/binding/c/mansrc/mpi_keyval_create.txt \
    src/binding/c/mansrc/mpi_comm_delete_attr.txt \
    src/binding/c/mansrc/mpi_attr_delete.txt \
    src/binding/c/mansrc/mpi_comm_free_keyval.txt \
    src/binding/c/mansrc/mpi_keyval_free.txt \
    src/binding/c/mansrc/mpi_comm_get_attr.txt \
    src/binding/c/mansrc/mpi_attr_get.txt \
    src/binding/c/mansrc/mpi_comm_set_attr.txt \
    src/binding/c/mansrc/mpi_attr_put.txt \
    src/binding/c/mansrc/mpi_type_create_keyval.txt \
    src/binding/c/mansrc/mpi_type_delete_attr.txt \
    src/binding/c/mansrc/mpi_type_free_keyval.txt \
    src/binding/c/mansrc/mpi_type_get_attr.txt \
    src/binding/c/mansrc/mpi_type_set_attr.txt \
    src/binding/c/mansrc/mpi_win_create_keyval.txt \
    src/binding/c/mansrc/mpi_win_delete_attr.txt \
    src/binding/c/mansrc/mpi_win_free_keyval.txt \
    src/binding/c/mansrc/mpi_win_get_attr.txt \
    src/binding/c/mansrc/mpi_win_set_attr.txt \
    src/binding/c/mansrc/mpix_op_create_x.txt \
    src/binding/c/mansrc/mpix_comm_create_errhandler_x.txt \
    src/binding/c/mansrc/mpix_win_create_errhandler_x.txt \
    src/binding/c/mansrc/mpix_file_create_errhandler_x.txt \
    src/binding/c/mansrc/mpix_session_create_errhandler_x.txt \
    src/binding/c/mansrc/mpi_allgather.txt \
    src/binding/c/mansrc/mpi_allgather_init.txt \
    src/binding/c/mansrc/mpi_allgatherv.txt \
    src/binding/c/mansrc/mpi_allgatherv_init.txt \
    src/binding/c/mansrc/mpi_allreduce.txt \
    src/binding/c/mansrc/mpi_allreduce_init.txt \
    src/binding/c/mansrc/mpi_alltoall.txt \
    src/binding/c/mansrc/mpi_alltoall_init.txt \
    src/binding/c/mansrc/mpi_alltoallv.txt \
    src/binding/c/mansrc/mpi_alltoallv_init.txt \
    src/binding/c/mansrc/mpi_alltoallw.txt \
    src/binding/c/mansrc/mpi_alltoallw_init.txt \
    src/binding/c/mansrc/mpi_barrier.txt \
    src/binding/c/mansrc/mpi_barrier_init.txt \
    src/binding/c/mansrc/mpi_bcast.txt \
    src/binding/c/mansrc/mpi_bcast_init.txt \
    src/binding/c/mansrc/mpi_exscan.txt \
    src/binding/c/mansrc/mpi_exscan_init.txt \
    src/binding/c/mansrc/mpi_gather.txt \
    src/binding/c/mansrc/mpi_gather_init.txt \
    src/binding/c/mansrc/mpi_gatherv.txt \
    src/binding/c/mansrc/mpi_gatherv_init.txt \
    src/binding/c/mansrc/mpi_iallgather.txt \
    src/binding/c/mansrc/mpi_iallgatherv.txt \
    src/binding/c/mansrc/mpi_iallreduce.txt \
    src/binding/c/mansrc/mpi_ialltoall.txt \
    src/binding/c/mansrc/mpi_ialltoallv.txt \
    src/binding/c/mansrc/mpi_ialltoallw.txt \
    src/binding/c/mansrc/mpi_ibarrier.txt \
    src/binding/c/mansrc/mpi_ibcast.txt \
    src/binding/c/mansrc/mpi_iexscan.txt \
    src/binding/c/mansrc/mpi_igather.txt \
    src/binding/c/mansrc/mpi_igatherv.txt \
    src/binding/c/mansrc/mpi_ineighbor_allgather.txt \
    src/binding/c/mansrc/mpi_ineighbor_allgatherv.txt \
    src/binding/c/mansrc/mpi_ineighbor_alltoall.txt \
    src/binding/c/mansrc/mpi_ineighbor_alltoallv.txt \
    src/binding/c/mansrc/mpi_ineighbor_alltoallw.txt \
    src/binding/c/mansrc/mpi_ireduce.txt \
    src/binding/c/mansrc/mpi_ireduce_scatter.txt \
    src/binding/c/mansrc/mpi_ireduce_scatter_block.txt \
    src/binding/c/mansrc/mpi_iscan.txt \
    src/binding/c/mansrc/mpi_iscatter.txt \
    src/binding/c/mansrc/mpi_iscatterv.txt \
    src/binding/c/mansrc/mpi_neighbor_allgather.txt \
    src/binding/c/mansrc/mpi_neighbor_allgather_init.txt \
    src/binding/c/mansrc/mpi_neighbor_allgatherv.txt \
    src/binding/c/mansrc/mpi_neighbor_allgatherv_init.txt \
    src/binding/c/mansrc/mpi_neighbor_alltoall.txt \
    src/binding/c/mansrc/mpi_neighbor_alltoall_init.txt \
    src/binding/c/mansrc/mpi_neighbor_alltoallv.txt \
    src/binding/c/mansrc/mpi_neighbor_alltoallv_init.txt \
    src/binding/c/mansrc/mpi_neighbor_alltoallw.txt \
    src/binding/c/mansrc/mpi_neighbor_alltoallw_init.txt \
    src/binding/c/mansrc/mpi_reduce.txt \
    src/binding/c/mansrc/mpi_reduce_init.txt \
    src/binding/c/mansrc/mpi_reduce_local.txt \
    src/binding/c/mansrc/mpi_reduce_scatter.txt \
    src/binding/c/mansrc/mpi_reduce_scatter_block.txt \
    src/binding/c/mansrc/mpi_reduce_scatter_block_init.txt \
    src/binding/c/mansrc/mpi_reduce_scatter_init.txt \
    src/binding/c/mansrc/mpi_scan.txt \
    src/binding/c/mansrc/mpi_scan_init.txt \
    src/binding/c/mansrc/mpi_scatter.txt \
    src/binding/c/mansrc/mpi_scatter_init.txt \
    src/binding/c/mansrc/mpi_scatterv.txt \
    src/binding/c/mansrc/mpi_scatterv_init.txt \
    src/binding/c/mansrc/mpi_comm_compare.txt \
    src/binding/c/mansrc/mpi_comm_create.txt \
    src/binding/c/mansrc/mpi_comm_create_group.txt \
    src/binding/c/mansrc/mpi_comm_dup.txt \
    src/binding/c/mansrc/mpi_comm_dup_with_info.txt \
    src/binding/c/mansrc/mpi_comm_free.txt \
    src/binding/c/mansrc/mpi_comm_get_info.txt \
    src/binding/c/mansrc/mpi_comm_get_name.txt \
    src/binding/c/mansrc/mpi_comm_group.txt \
    src/binding/c/mansrc/mpi_comm_idup.txt \
    src/binding/c/mansrc/mpi_comm_idup_with_info.txt \
    src/binding/c/mansrc/mpi_comm_rank.txt \
    src/binding/c/mansrc/mpi_comm_remote_group.txt \
    src/binding/c/mansrc/mpi_comm_remote_size.txt \
    src/binding/c/mansrc/mpi_comm_set_info.txt \
    src/binding/c/mansrc/mpi_comm_set_name.txt \
    src/binding/c/mansrc/mpi_comm_size.txt \
    src/binding/c/mansrc/mpi_comm_split.txt \
    src/binding/c/mansrc/mpi_comm_split_type.txt \
    src/binding/c/mansrc/mpi_comm_test_inter.txt \
    src/binding/c/mansrc/mpi_intercomm_create.txt \
    src/binding/c/mansrc/mpi_intercomm_create_from_groups.txt \
    src/binding/c/mansrc/mpi_intercomm_merge.txt \
    src/binding/c/mansrc/mpix_comm_test_threadcomm.txt \
    src/binding/c/mansrc/mpix_comm_revoke.txt \
    src/binding/c/mansrc/mpix_comm_shrink.txt \
    src/binding/c/mansrc/mpix_comm_failure_ack.txt \
    src/binding/c/mansrc/mpix_comm_failure_get_acked.txt \
    src/binding/c/mansrc/mpix_comm_agree.txt \
    src/binding/c/mansrc/mpix_comm_get_failed.txt \
    src/binding/c/mansrc/mpi_get_address.txt \
    src/binding/c/mansrc/mpi_address.txt \
    src/binding/c/mansrc/mpi_get_count.txt \
    src/binding/c/mansrc/mpi_get_elements.txt \
    src/binding/c/mansrc/mpi_get_elements_x.txt \
    src/binding/c/mansrc/mpi_pack.txt \
    src/binding/c/mansrc/mpi_pack_external.txt \
    src/binding/c/mansrc/mpi_pack_external_size.txt \
    src/binding/c/mansrc/mpi_pack_size.txt \
    src/binding/c/mansrc/mpi_status_set_elements.txt \
    src/binding/c/mansrc/mpi_status_set_elements_x.txt \
    src/binding/c/mansrc/mpi_type_commit.txt \
    src/binding/c/mansrc/mpi_type_contiguous.txt \
    src/binding/c/mansrc/mpi_type_create_darray.txt \
    src/binding/c/mansrc/mpi_type_create_f90_complex.txt \
    src/binding/c/mansrc/mpi_type_create_f90_integer.txt \
    src/binding/c/mansrc/mpi_type_create_f90_real.txt \
    src/binding/c/mansrc/mpi_type_create_hindexed.txt \
    src/binding/c/mansrc/mpi_type_hindexed.txt \
    src/binding/c/mansrc/mpi_type_create_hindexed_block.txt \
    src/binding/c/mansrc/mpi_type_create_hvector.txt \
    src/binding/c/mansrc/mpi_type_hvector.txt \
    src/binding/c/mansrc/mpi_type_create_indexed_block.txt \
    src/binding/c/mansrc/mpi_type_create_resized.txt \
    src/binding/c/mansrc/mpi_type_create_struct.txt \
    src/binding/c/mansrc/mpi_type_struct.txt \
    src/binding/c/mansrc/mpi_type_create_subarray.txt \
    src/binding/c/mansrc/mpi_type_dup.txt \
    src/binding/c/mansrc/mpi_type_free.txt \
    src/binding/c/mansrc/mpi_type_get_contents.txt \
    src/binding/c/mansrc/mpi_type_get_envelope.txt \
    src/binding/c/mansrc/mpi_type_get_extent.txt \
    src/binding/c/mansrc/mpi_type_get_extent_x.txt \
    src/binding/c/mansrc/mpi_type_get_name.txt \
    src/binding/c/mansrc/mpi_type_get_true_extent.txt \
    src/binding/c/mansrc/mpi_type_get_true_extent_x.txt \
    src/binding/c/mansrc/mpi_type_get_value_index.txt \
    src/binding/c/mansrc/mpi_type_indexed.txt \
    src/binding/c/mansrc/mpi_type_match_size.txt \
    src/binding/c/mansrc/mpi_type_set_name.txt \
    src/binding/c/mansrc/mpi_type_size.txt \
    src/binding/c/mansrc/mpi_type_size_x.txt \
    src/binding/c/mansrc/mpi_type_vector.txt \
    src/binding/c/mansrc/mpi_unpack.txt \
    src/binding/c/mansrc/mpi_unpack_external.txt \
    src/binding/c/mansrc/mpi_type_extent.txt \
    src/binding/c/mansrc/mpi_type_lb.txt \
    src/binding/c/mansrc/mpi_type_ub.txt \
    src/binding/c/mansrc/mpix_type_iov_len.txt \
    src/binding/c/mansrc/mpix_type_iov.txt \
    src/binding/c/mansrc/mpi_add_error_class.txt \
    src/binding/c/mansrc/mpi_add_error_code.txt \
    src/binding/c/mansrc/mpi_add_error_string.txt \
    src/binding/c/mansrc/mpi_comm_call_errhandler.txt \
    src/binding/c/mansrc/mpi_comm_create_errhandler.txt \
    src/binding/c/mansrc/mpi_errhandler_create.txt \
    src/binding/c/mansrc/mpi_comm_get_errhandler.txt \
    src/binding/c/mansrc/mpi_errhandler_get.txt \
    src/binding/c/mansrc/mpi_comm_set_errhandler.txt \
    src/binding/c/mansrc/mpi_errhandler_set.txt \
    src/binding/c/mansrc/mpi_errhandler_free.txt \
    src/binding/c/mansrc/mpi_error_class.txt \
    src/binding/c/mansrc/mpi_error_string.txt \
    src/binding/c/mansrc/mpi_file_call_errhandler.txt \
    src/binding/c/mansrc/mpi_file_create_errhandler.txt \
    src/binding/c/mansrc/mpi_file_get_errhandler.txt \
    src/binding/c/mansrc/mpi_file_set_errhandler.txt \
    src/binding/c/mansrc/mpi_remove_error_class.txt \
    src/binding/c/mansrc/mpi_remove_error_code.txt \
    src/binding/c/mansrc/mpi_remove_error_string.txt \
    src/binding/c/mansrc/mpi_session_call_errhandler.txt \
    src/binding/c/mansrc/mpi_session_create_errhandler.txt \
    src/binding/c/mansrc/mpi_session_get_errhandler.txt \
    src/binding/c/mansrc/mpi_session_set_errhandler.txt \
    src/binding/c/mansrc/mpi_win_call_errhandler.txt \
    src/binding/c/mansrc/mpi_win_create_errhandler.txt \
    src/binding/c/mansrc/mpi_win_get_errhandler.txt \
    src/binding/c/mansrc/mpi_win_set_errhandler.txt \
    src/binding/c/mansrc/mpi_comm_c2f.txt \
    src/binding/c/mansrc/mpi_comm_f2c.txt \
    src/binding/c/mansrc/mpi_errhandler_c2f.txt \
    src/binding/c/mansrc/mpi_errhandler_f2c.txt \
    src/binding/c/mansrc/mpi_group_c2f.txt \
    src/binding/c/mansrc/mpi_group_f2c.txt \
    src/binding/c/mansrc/mpi_info_c2f.txt \
    src/binding/c/mansrc/mpi_info_f2c.txt \
    src/binding/c/mansrc/mpi_message_c2f.txt \
    src/binding/c/mansrc/mpi_message_f2c.txt \
    src/binding/c/mansrc/mpi_op_c2f.txt \
    src/binding/c/mansrc/mpi_op_f2c.txt \
    src/binding/c/mansrc/mpi_request_c2f.txt \
    src/binding/c/mansrc/mpi_request_f2c.txt \
    src/binding/c/mansrc/mpi_session_c2f.txt \
    src/binding/c/mansrc/mpi_session_f2c.txt \
    src/binding/c/mansrc/mpi_status_c2f.txt \
    src/binding/c/mansrc/mpi_status_c2f08.txt \
    src/binding/c/mansrc/mpi_status_f082c.txt \
    src/binding/c/mansrc/mpi_status_f082f.txt \
    src/binding/c/mansrc/mpi_status_f2c.txt \
    src/binding/c/mansrc/mpi_status_f2f08.txt \
    src/binding/c/mansrc/mpi_type_c2f.txt \
    src/binding/c/mansrc/mpi_type_f2c.txt \
    src/binding/c/mansrc/mpi_win_c2f.txt \
    src/binding/c/mansrc/mpi_win_f2c.txt \
    src/binding/c/mansrc/mpi_group_compare.txt \
    src/binding/c/mansrc/mpi_group_difference.txt \
    src/binding/c/mansrc/mpi_group_excl.txt \
    src/binding/c/mansrc/mpi_group_free.txt \
    src/binding/c/mansrc/mpi_group_incl.txt \
    src/binding/c/mansrc/mpi_group_intersection.txt \
    src/binding/c/mansrc/mpi_group_range_excl.txt \
    src/binding/c/mansrc/mpi_group_range_incl.txt \
    src/binding/c/mansrc/mpi_group_rank.txt \
    src/binding/c/mansrc/mpi_group_size.txt \
    src/binding/c/mansrc/mpi_group_translate_ranks.txt \
    src/binding/c/mansrc/mpi_group_union.txt \
    src/binding/c/mansrc/mpi_info_create.txt \
    src/binding/c/mansrc/mpi_info_create_env.txt \
    src/binding/c/mansrc/mpi_info_delete.txt \
    src/binding/c/mansrc/mpi_info_dup.txt \
    src/binding/c/mansrc/mpi_info_free.txt \
    src/binding/c/mansrc/mpi_info_get.txt \
    src/binding/c/mansrc/mpi_info_get_nkeys.txt \
    src/binding/c/mansrc/mpi_info_get_nthkey.txt \
    src/binding/c/mansrc/mpi_info_get_string.txt \
    src/binding/c/mansrc/mpi_info_get_valuelen.txt \
    src/binding/c/mansrc/mpi_info_set.txt \
    src/binding/c/mansrc/mpix_info_set_hex.txt \
    src/binding/c/mansrc/mpi_abort.txt \
    src/binding/c/mansrc/mpi_comm_create_from_group.txt \
    src/binding/c/mansrc/mpi_finalize.txt \
    src/binding/c/mansrc/mpi_finalized.txt \
    src/binding/c/mansrc/mpi_group_from_session_pset.txt \
    src/binding/c/mansrc/mpi_init.txt \
    src/binding/c/mansrc/mpi_init_thread.txt \
    src/binding/c/mansrc/mpi_initialized.txt \
    src/binding/c/mansrc/mpi_is_thread_main.txt \
    src/binding/c/mansrc/mpi_query_thread.txt \
    src/binding/c/mansrc/mpi_session_finalize.txt \
    src/binding/c/mansrc/mpi_session_get_info.txt \
    src/binding/c/mansrc/mpi_session_get_nth_pset.txt \
    src/binding/c/mansrc/mpi_session_get_num_psets.txt \
    src/binding/c/mansrc/mpi_session_get_pset_info.txt \
    src/binding/c/mansrc/mpi_session_init.txt \
    src/binding/c/mansrc/mpi_aint_add.txt \
    src/binding/c/mansrc/mpi_aint_diff.txt \
    src/binding/c/mansrc/mpi_get_library_version.txt \
    src/binding/c/mansrc/mpi_get_processor_name.txt \
    src/binding/c/mansrc/mpi_get_version.txt \
    src/binding/c/mansrc/mpi_pcontrol.txt \
    src/binding/c/mansrc/mpix_gpu_query_support.txt \
    src/binding/c/mansrc/mpix_query_cuda_support.txt \
    src/binding/c/mansrc/mpix_query_ze_support.txt \
    src/binding/c/mansrc/mpix_query_hip_support.txt \
    src/binding/c/mansrc/mpi_t_category_changed.txt \
    src/binding/c/mansrc/mpi_t_category_get_categories.txt \
    src/binding/c/mansrc/mpi_t_category_get_cvars.txt \
    src/binding/c/mansrc/mpi_t_category_get_events.txt \
    src/binding/c/mansrc/mpi_t_category_get_index.txt \
    src/binding/c/mansrc/mpi_t_category_get_info.txt \
    src/binding/c/mansrc/mpi_t_category_get_num.txt \
    src/binding/c/mansrc/mpi_t_category_get_num_events.txt \
    src/binding/c/mansrc/mpi_t_category_get_pvars.txt \
    src/binding/c/mansrc/mpi_t_cvar_get_index.txt \
    src/binding/c/mansrc/mpi_t_cvar_get_info.txt \
    src/binding/c/mansrc/mpi_t_cvar_get_num.txt \
    src/binding/c/mansrc/mpi_t_cvar_handle_alloc.txt \
    src/binding/c/mansrc/mpi_t_cvar_handle_free.txt \
    src/binding/c/mansrc/mpi_t_cvar_read.txt \
    src/binding/c/mansrc/mpi_t_cvar_write.txt \
    src/binding/c/mansrc/mpi_t_enum_get_info.txt \
    src/binding/c/mansrc/mpi_t_enum_get_item.txt \
    src/binding/c/mansrc/mpi_t_event_callback_get_info.txt \
    src/binding/c/mansrc/mpi_t_event_callback_set_info.txt \
    src/binding/c/mansrc/mpi_t_event_copy.txt \
    src/binding/c/mansrc/mpi_t_event_get_index.txt \
    src/binding/c/mansrc/mpi_t_event_get_info.txt \
    src/binding/c/mansrc/mpi_t_event_get_num.txt \
    src/binding/c/mansrc/mpi_t_event_get_source.txt \
    src/binding/c/mansrc/mpi_t_event_get_timestamp.txt \
    src/binding/c/mansrc/mpi_t_event_handle_alloc.txt \
    src/binding/c/mansrc/mpi_t_event_handle_free.txt \
    src/binding/c/mansrc/mpi_t_event_handle_get_info.txt \
    src/binding/c/mansrc/mpi_t_event_handle_set_info.txt \
    src/binding/c/mansrc/mpi_t_event_read.txt \
    src/binding/c/mansrc/mpi_t_event_register_callback.txt \
    src/binding/c/mansrc/mpi_t_event_set_dropped_handler.txt \
    src/binding/c/mansrc/mpi_t_finalize.txt \
    src/binding/c/mansrc/mpi_t_init_thread.txt \
    src/binding/c/mansrc/mpi_t_pvar_get_index.txt \
    src/binding/c/mansrc/mpi_t_pvar_get_info.txt \
    src/binding/c/mansrc/mpi_t_pvar_get_num.txt \
    src/binding/c/mansrc/mpi_t_pvar_handle_alloc.txt \
    src/binding/c/mansrc/mpi_t_pvar_handle_free.txt \
    src/binding/c/mansrc/mpi_t_pvar_read.txt \
    src/binding/c/mansrc/mpi_t_pvar_readreset.txt \
    src/binding/c/mansrc/mpi_t_pvar_reset.txt \
    src/binding/c/mansrc/mpi_t_pvar_session_create.txt \
    src/binding/c/mansrc/mpi_t_pvar_session_free.txt \
    src/binding/c/mansrc/mpi_t_pvar_start.txt \
    src/binding/c/mansrc/mpi_t_pvar_stop.txt \
    src/binding/c/mansrc/mpi_t_pvar_write.txt \
    src/binding/c/mansrc/mpi_t_source_get_info.txt \
    src/binding/c/mansrc/mpi_t_source_get_num.txt \
    src/binding/c/mansrc/mpi_t_source_get_timestamp.txt \
    src/binding/c/mansrc/mpi_op_commutative.txt \
    src/binding/c/mansrc/mpi_op_create.txt \
    src/binding/c/mansrc/mpi_op_free.txt \
    src/binding/c/mansrc/mpi_parrived.txt \
    src/binding/c/mansrc/mpi_pready.txt \
    src/binding/c/mansrc/mpi_pready_list.txt \
    src/binding/c/mansrc/mpi_pready_range.txt \
    src/binding/c/mansrc/mpi_precv_init.txt \
    src/binding/c/mansrc/mpi_psend_init.txt \
    src/binding/c/mansrc/mpi_bsend.txt \
    src/binding/c/mansrc/mpi_bsend_init.txt \
    src/binding/c/mansrc/mpi_buffer_attach.txt \
    src/binding/c/mansrc/mpi_buffer_detach.txt \
    src/binding/c/mansrc/mpi_buffer_flush.txt \
    src/binding/c/mansrc/mpi_buffer_iflush.txt \
    src/binding/c/mansrc/mpi_comm_attach_buffer.txt \
    src/binding/c/mansrc/mpi_comm_detach_buffer.txt \
    src/binding/c/mansrc/mpi_comm_flush_buffer.txt \
    src/binding/c/mansrc/mpi_comm_iflush_buffer.txt \
    src/binding/c/mansrc/mpi_ibsend.txt \
    src/binding/c/mansrc/mpi_improbe.txt \
    src/binding/c/mansrc/mpi_imrecv.txt \
    src/binding/c/mansrc/mpi_iprobe.txt \
    src/binding/c/mansrc/mpi_irecv.txt \
    src/binding/c/mansrc/mpi_irsend.txt \
    src/binding/c/mansrc/mpi_isend.txt \
    src/binding/c/mansrc/mpi_isendrecv.txt \
    src/binding/c/mansrc/mpi_isendrecv_replace.txt \
    src/binding/c/mansrc/mpi_issend.txt \
    src/binding/c/mansrc/mpi_mprobe.txt \
    src/binding/c/mansrc/mpi_mrecv.txt \
    src/binding/c/mansrc/mpi_probe.txt \
    src/binding/c/mansrc/mpi_recv.txt \
    src/binding/c/mansrc/mpi_recv_init.txt \
    src/binding/c/mansrc/mpi_rsend.txt \
    src/binding/c/mansrc/mpi_rsend_init.txt \
    src/binding/c/mansrc/mpi_send.txt \
    src/binding/c/mansrc/mpi_send_init.txt \
    src/binding/c/mansrc/mpi_sendrecv.txt \
    src/binding/c/mansrc/mpi_sendrecv_replace.txt \
    src/binding/c/mansrc/mpi_session_attach_buffer.txt \
    src/binding/c/mansrc/mpi_session_detach_buffer.txt \
    src/binding/c/mansrc/mpi_session_flush_buffer.txt \
    src/binding/c/mansrc/mpi_session_iflush_buffer.txt \
    src/binding/c/mansrc/mpi_ssend.txt \
    src/binding/c/mansrc/mpi_ssend_init.txt \
    src/binding/c/mansrc/mpi_cancel.txt \
    src/binding/c/mansrc/mpi_grequest_complete.txt \
    src/binding/c/mansrc/mpi_grequest_start.txt \
    src/binding/c/mansrc/mpi_request_free.txt \
    src/binding/c/mansrc/mpi_request_get_status.txt \
    src/binding/c/mansrc/mpi_request_get_status_all.txt \
    src/binding/c/mansrc/mpi_request_get_status_any.txt \
    src/binding/c/mansrc/mpi_request_get_status_some.txt \
    src/binding/c/mansrc/mpi_start.txt \
    src/binding/c/mansrc/mpi_startall.txt \
    src/binding/c/mansrc/mpi_status_get_error.txt \
    src/binding/c/mansrc/mpi_status_get_source.txt \
    src/binding/c/mansrc/mpi_status_get_tag.txt \
    src/binding/c/mansrc/mpi_status_set_error.txt \
    src/binding/c/mansrc/mpi_status_set_source.txt \
    src/binding/c/mansrc/mpi_status_set_tag.txt \
    src/binding/c/mansrc/mpi_status_set_cancelled.txt \
    src/binding/c/mansrc/mpi_test.txt \
    src/binding/c/mansrc/mpi_test_cancelled.txt \
    src/binding/c/mansrc/mpi_testall.txt \
    src/binding/c/mansrc/mpi_testany.txt \
    src/binding/c/mansrc/mpi_testsome.txt \
    src/binding/c/mansrc/mpi_wait.txt \
    src/binding/c/mansrc/mpi_waitall.txt \
    src/binding/c/mansrc/mpi_waitany.txt \
    src/binding/c/mansrc/mpi_waitsome.txt \
    src/binding/c/mansrc/grequest_start_x.txt \
    src/binding/c/mansrc/mpix_grequest_class_create.txt \
    src/binding/c/mansrc/mpix_grequest_class_allocate.txt \
    src/binding/c/mansrc/mpix_request_is_complete.txt \
    src/binding/c/mansrc/mpi_accumulate.txt \
    src/binding/c/mansrc/mpi_alloc_mem.txt \
    src/binding/c/mansrc/mpi_compare_and_swap.txt \
    src/binding/c/mansrc/mpi_fetch_and_op.txt \
    src/binding/c/mansrc/mpi_free_mem.txt \
    src/binding/c/mansrc/mpi_get.txt \
    src/binding/c/mansrc/mpi_get_accumulate.txt \
    src/binding/c/mansrc/mpi_put.txt \
    src/binding/c/mansrc/mpi_raccumulate.txt \
    src/binding/c/mansrc/mpi_rget.txt \
    src/binding/c/mansrc/mpi_rget_accumulate.txt \
    src/binding/c/mansrc/mpi_rput.txt \
    src/binding/c/mansrc/mpi_win_allocate.txt \
    src/binding/c/mansrc/mpi_win_allocate_shared.txt \
    src/binding/c/mansrc/mpi_win_attach.txt \
    src/binding/c/mansrc/mpi_win_complete.txt \
    src/binding/c/mansrc/mpi_win_create.txt \
    src/binding/c/mansrc/mpi_win_create_dynamic.txt \
    src/binding/c/mansrc/mpi_win_detach.txt \
    src/binding/c/mansrc/mpi_win_fence.txt \
    src/binding/c/mansrc/mpi_win_flush.txt \
    src/binding/c/mansrc/mpi_win_flush_all.txt \
    src/binding/c/mansrc/mpi_win_flush_local.txt \
    src/binding/c/mansrc/mpi_win_flush_local_all.txt \
    src/binding/c/mansrc/mpi_win_free.txt \
    src/binding/c/mansrc/mpi_win_get_group.txt \
    src/binding/c/mansrc/mpi_win_get_info.txt \
    src/binding/c/mansrc/mpi_win_get_name.txt \
    src/binding/c/mansrc/mpi_win_lock.txt \
    src/binding/c/mansrc/mpi_win_lock_all.txt \
    src/binding/c/mansrc/mpi_win_post.txt \
    src/binding/c/mansrc/mpi_win_set_info.txt \
    src/binding/c/mansrc/mpi_win_set_name.txt \
    src/binding/c/mansrc/mpi_win_shared_query.txt \
    src/binding/c/mansrc/mpi_win_start.txt \
    src/binding/c/mansrc/mpi_win_sync.txt \
    src/binding/c/mansrc/mpi_win_test.txt \
    src/binding/c/mansrc/mpi_win_unlock.txt \
    src/binding/c/mansrc/mpi_win_unlock_all.txt \
    src/binding/c/mansrc/mpi_win_wait.txt \
    src/binding/c/mansrc/mpi_close_port.txt \
    src/binding/c/mansrc/mpi_comm_accept.txt \
    src/binding/c/mansrc/mpi_comm_connect.txt \
    src/binding/c/mansrc/mpi_comm_disconnect.txt \
    src/binding/c/mansrc/mpi_comm_get_parent.txt \
    src/binding/c/mansrc/mpi_comm_join.txt \
    src/binding/c/mansrc/mpi_comm_spawn.txt \
    src/binding/c/mansrc/mpi_comm_spawn_multiple.txt \
    src/binding/c/mansrc/mpi_lookup_name.txt \
    src/binding/c/mansrc/mpi_open_port.txt \
    src/binding/c/mansrc/mpi_publish_name.txt \
    src/binding/c/mansrc/mpi_unpublish_name.txt \
    src/binding/c/mansrc/mpix_stream_create.txt \
    src/binding/c/mansrc/mpix_stream_free.txt \
    src/binding/c/mansrc/mpix_stream_comm_create.txt \
    src/binding/c/mansrc/mpix_stream_comm_create_multiplex.txt \
    src/binding/c/mansrc/mpix_comm_get_stream.txt \
    src/binding/c/mansrc/mpix_stream_progress.txt \
    src/binding/c/mansrc/mpix_start_progress_thread.txt \
    src/binding/c/mansrc/mpix_stop_progress_thread.txt \
    src/binding/c/mansrc/mpix_stream_send.txt \
    src/binding/c/mansrc/mpix_stream_isend.txt \
    src/binding/c/mansrc/mpix_stream_recv.txt \
    src/binding/c/mansrc/mpix_stream_irecv.txt \
    src/binding/c/mansrc/mpix_send_enqueue.txt \
    src/binding/c/mansrc/mpix_recv_enqueue.txt \
    src/binding/c/mansrc/mpix_isend_enqueue.txt \
    src/binding/c/mansrc/mpix_irecv_enqueue.txt \
    src/binding/c/mansrc/mpix_wait_enqueue.txt \
    src/binding/c/mansrc/mpix_waitall_enqueue.txt \
    src/binding/c/mansrc/mpix_allreduce_enqueue.txt \
    src/binding/c/mansrc/mpix_threadcomm_init.txt \
    src/binding/c/mansrc/mpix_threadcomm_free.txt \
    src/binding/c/mansrc/mpix_threadcomm_start.txt \
    src/binding/c/mansrc/mpix_threadcomm_finish.txt \
    src/binding/c/mansrc/mpi_wtick.txt \
    src/binding/c/mansrc/mpi_wtime.txt \
    src/binding/c/mansrc/mpi_cart_coords.txt \
    src/binding/c/mansrc/mpi_cart_create.txt \
    src/binding/c/mansrc/mpi_cart_get.txt \
    src/binding/c/mansrc/mpi_cart_map.txt \
    src/binding/c/mansrc/mpi_cart_rank.txt \
    src/binding/c/mansrc/mpi_cart_shift.txt \
    src/binding/c/mansrc/mpi_cart_sub.txt \
    src/binding/c/mansrc/mpi_cartdim_get.txt \
    src/binding/c/mansrc/mpi_dims_create.txt \
    src/binding/c/mansrc/mpi_dist_graph_create.txt \
    src/binding/c/mansrc/mpi_dist_graph_create_adjacent.txt \
    src/binding/c/mansrc/mpi_dist_graph_neighbors.txt \
    src/binding/c/mansrc/mpi_dist_graph_neighbors_count.txt \
    src/binding/c/mansrc/mpi_get_hw_resource_info.txt \
    src/binding/c/mansrc/mpi_graph_create.txt \
    src/binding/c/mansrc/mpi_graph_get.txt \
    src/binding/c/mansrc/mpi_graph_map.txt \
    src/binding/c/mansrc/mpi_graph_neighbors.txt \
    src/binding/c/mansrc/mpi_graph_neighbors_count.txt \
    src/binding/c/mansrc/mpi_graphdims_get.txt \
    src/binding/c/mansrc/mpi_topo_test.txt
